server:
  port: 10010 #网关的端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos
    gateway:
      routes:  #网关路由的配置
        - id: user-service #路由的id,名称唯一即可
          #uri: http://127.0.0.1:8081 #路由地址
          uri: lb://userservice #路由的地址 lb:负载均衡,跟上服务的名称
          predicates: #路由的断言,判断请求是否符合路由的规则(条件)
            - Path=/user/** #按照路径进行匹配
          #请求头过滤器
#          filters:
#            - AddRequestHeader=Truth,Hello cloud!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      #全局过滤器
      default-filters:
        - AddRequestHeader=Truth,Hello cloud!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8081"
              - "http://localhost:8082"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期