server:
  port: 10010 #网关的端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos
    gateway:
      routes:  #网关路由的配置
        - id: user-service #路由的id,名称唯一即可
          #uri: http://127.0.0.1:8081 #路由地址
          uri: lb://userservice #路由的地址 lb:负载均衡,跟上服务的名称
          predicates: #路由的断言,判断请求是否符合路由的规则(条件)
            - Path=/user/** #按照路径进行匹配
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**